// eslint.config.mjs — ESLint 9 config for the Joker Store project
// Supports: client-side JS (browser) + server-side JS (Node.js)
// Goal: Catch bugs, security issues, and basic code quality

export default [
  {
    ignores: ['node_modules/**', 'dist/**', '.git/**', '.kilo/**'],
  },
  // === Server-side files (CommonJS) ===
  {
    files: ['server.js', 'routes/**/*.js', 'controllers/**/*.js', 'models/**/*.js', 'middleware/**/*.js', 'scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
      },
    },
    rules: {
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-proto': 'error',
      'no-unused-vars': ['warn', {
        args: 'after-used',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
      }],
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-console': 'off',
      'no-cond-assign': 'error',
      'no-empty': 'warn',
      'no-useless-escape': 'warn',
      'no-dupe-keys': 'error',
      'no-sparse-arrays': 'error',
      'no-prototype-builtins': 'warn',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'warn',
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
      'no-shadow': 'warn',
      'prefer-template': 'warn',
      'prefer-destructuring': 'warn',
      'no-process-exit': 'off',
    },
  },
  // === Client-side files (ES Modules for browser) ===
  {
    files: ['public/**/*.js', 'private/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        FormData: 'readonly',
        URLSearchParams: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        HTMLElement: 'readonly',
        Event: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Audio: 'readonly',
        history: 'readonly',
        location: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        CustomEvent: 'readonly',
        Blob: 'readonly',
        Promise: 'readonly',
        logout: 'readonly',
        showProductDetails: 'readonly',
        showProductDetails: 'readonly',
        formatItem: 'readonly',
        detectRegion: 'readonly',
        getCurrentLanguage: 'readonly',
        showAllCategories: 'readonly',
        selectCategory: 'readonly',
        updateCartUI: 'readonly',
        showToast: 'readonly',
        initToastContainer: 'readonly',
        Chart: 'readonly',
      },
    },
    rules: {
      'no-eval': 'error',
      'no-new-func': 'error',
      'no-proto': 'error',
      'no-unused-vars': ['warn', {
        args: 'after-used',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
      }],
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-unreachable': 'error',
      'no-console': 'off',
      'no-cond-assign': 'error',
      'no-empty': 'warn',
      'no-useless-escape': 'warn',
      'no-dupe-keys': 'error',
      'no-sparse-arrays': 'error',
      'no-prototype-builtins': 'warn',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'warn',
      'prefer-const': 'error',
      'no-var': 'error',
      'eqeqeq': ['error', 'always'],
      'no-shadow': 'warn',
      'prefer-template': 'warn',
      'prefer-destructuring': 'warn',
    },
  },
  // === Service Worker (browser worker globals) ===
  {
    files: ['public/sw.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        clients: 'readonly',
        importScripts: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'off',
    },
  },
];
